In [2]:
import pandas as pd
import datetime

In [161]:
df = pd.read_excel(
    r"C:\Git_test\Project 2 Docs\Data Sets\consumerpriceinflationdetailedreferencetables.xlsx",
    sheet_name='Table 37', header=6
)

In [162]:
print(df.index)
print(df.head(10))

RangeIndex(start=0, stop=480, step=1)
   index date                    name  CPIH ALL ITEMS  \
0       198801.0  1988-01-01 00:00:00          46.851
1       198802.0  1988-02-01 00:00:00          46.998
2       198803.0  1988-03-01 00:00:00          47.202
3       198804.0  1988-04-01 00:00:00          47.801
4       198805.0  1988-05-01 00:00:00          48.044
5       198806.0  1988-06-01 00:00:00          48.210
6       198807.0  1988-07-01 00:00:00          48.233
7       198808.0  1988-08-01 00:00:00          48.491
8       198809.0  1988-09-01 00:00:00          48.716
9       198810.0  1988-10-01 00:00:00          49.045

   FOOD AND NON-ALCOHOLIC BEVERAGES    FOOD  BREAD & CEREALS    MEAT    FISH  \
0                            47.901  48.244           50.053  53.741  43.321
1                            48.174  48.501           50.353  53.386  43.670
2                            48.324  48.643           50.311  53.721  43.130
3                            48.592  48.894           50.548  53.736  43.151
4                            48.714  48.968           50.970  54.186  42.799
5                            48.793  49.004           51.040  54.685  42.942
6                            48.355  48.483           51.199  54.403  42.778
7                            48.583  48.697           51.212  54.712  42.502
8                            48.765  48.866           51.483  54.874  42.837
9                            48.838  48.936           51.609  54.603  42.555

   MILK, CHEESE & EGGS  OILS & FATS  ...  Energy, Food, Alcohol & Tobacco  \
0               48.488       45.461  ...                           36.679
1               48.523       45.921  ...                           36.761
2               48.551       46.108  ...                           36.831
3               48.861       46.249  ...                           37.198
4               48.770       46.346  ...                           37.360
5               48.588       46.244  ...                           37.550
6               48.586       46.512  ...                           37.457
7               49.455       47.122  ...                           37.536
8               49.560       47.904  ...                           37.632
9               49.834       48.293  ...                           37.684

   Energy & Non-processed Food  Energy & Seasonal Food  \
0                       37.044                  33.852
1                       37.084                  33.968
2                       37.144                  33.976
3                       37.531                  34.434
4                       37.688                  34.535
5                       38.031                  34.848
6                       37.779                  34.602
7                       37.761                  34.521
8                       37.836                  34.578
9                       37.802                  34.590

   Education, Health & Social Protection  CPIH excluding tobacco  \
0                                 22.323                  48.106
1                                 22.340                  48.259
2                                 22.455                  48.476
3                                 22.510                  49.085
4                                 22.544                  49.336
5                                 22.577                  49.514
6                                 22.591                  49.539
7                                 22.662                  49.811
8                                 23.517                  50.048
9                                 23.583                  50.389

   Industrial Goods  Miscellaneous and Other Services  \
0            78.883                            26.778
1            79.037                            26.915
2            79.399                            26.968
3            80.067                            27.098
4            80.623                            27.213
5            81.105                            27.308
6            81.166                            27.346
7            81.373                            27.494
8            81.748                            28.338
9            82.221                            28.385

   CPIH excluding owner occupiers' housing costs  CPIH excluding council tax  \
0                                         47.734                      47.304
1                                         47.884                      47.455
2                                         48.042                      47.667
3                                         48.707                      48.184
4                                         48.941                      48.435
5                                         49.130                      48.608
6                                         49.119                      48.631
7                                         49.273                      48.898
8                                         49.507                      49.131
9                                         49.722                      49.472

   CPIH excluding owner occupiers' housing costs and council tax and rates
0                                             48.329
1                                             48.486
2                                             48.652
3                                             49.214
4                                             49.459
5                                             49.657
6                                             49.645
7                                             49.806
8                                             50.050
9                                             50.275

[10 rows x 181 columns]

In [163]:
print(df.columns)

Index(['index date   ', 'name', 'CPIH ALL ITEMS',
       'FOOD AND NON-ALCOHOLIC BEVERAGES', 'FOOD', 'BREAD & CEREALS', 'MEAT',
       'FISH', 'MILK, CHEESE & EGGS', 'OILS & FATS',
       ...
       'Energy, Food, Alcohol & Tobacco', 'Energy & Non-processed Food',
       'Energy & Seasonal Food', 'Education, Health & Social Protection',
       'CPIH excluding tobacco', 'Industrial Goods',
       'Miscellaneous and Other Services',
       'CPIH excluding owner occupiers' housing costs',
       'CPIH excluding council tax',
       'CPIH excluding owner occupiers' housing costs and council tax and rates'],
      dtype='object', length=181)

In [164]:
df.columns = df.columns.str.strip().str.title()

df

,Index Date,Name,Cpih All Items,Food And Non-Alcoholic Beverages,Food,Bread & Cereals,Meat,Fish,"Milk, Cheese & Eggs",Oils & Fats,...,"Energy, Food, Alcohol & Tobacco",Energy & Non-Processed Food,Energy & Seasonal Food,"Education, Health & Social Protection",Cpih Excluding Tobacco,Industrial Goods,Miscellaneous And Other Services,Cpih Excluding Owner Occupiers' Housing Costs,Cpih Excluding Council Tax,Cpih Excluding Owner Occupiers' Housing Costs And Council Tax And Rates
0,198801.0,1988-01-01 00:00:00,46.851,47.901,48.244,50.053,53.741,43.321,48.488,45.461,...,36.679,37.044,33.852,22.323,48.106,78.883,26.778,47.734,47.304,48.329
1,198802.0,1988-02-01 00:00:00,46.998,48.174,48.501,50.353,53.386,43.670,48.523,45.921,...,36.761,37.084,33.968,22.340,48.259,79.037,26.915,47.884,47.455,48.486
2,198803.0,1988-03-01 00:00:00,47.202,48.324,48.643,50.311,53.721,43.130,48.551,46.108,...,36.831,37.144,33.976,22.455,48.476,79.399,26.968,48.042,47.667,48.652
3,198804.0,1988-04-01 00:00:00,47.801,48.592,48.894,50.548,53.736,43.151,48.861,46.249,...,37.198,37.531,34.434,22.510,49.085,80.067,27.098,48.707,48.184,49.214
4,198805.0,1988-05-01 00:00:00,48.044,48.714,48.968,50.970,54.186,42.799,48.770,46.346,...,37.360,37.688,34.535,22.544,49.336,80.623,27.213,48.941,48.435,49.459
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
475,NaN,Full historic series for each of the re-refere...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
476,NaN,Regular re-referencing of indices is methodolo...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
477,NaN,Please note that re-referencing does not impac...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
478,NaN,it is important to use indices that are refere...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
479,NaN,"For more information, please contact cpi@ons.g...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [165]:
print(df.iloc[430:])

     Index Date                                               Name  \
430    202311.0                                2023-11-01 00:00:00
431    202312.0                                2023-12-01 00:00:00
432    202401.0                                2024-01-01 00:00:00
433    202402.0                                2024-02-01 00:00:00
434    202403.0                                2024-03-01 00:00:00
435    202404.0                                2024-04-01 00:00:00
436    202405.0                                2024-05-01 00:00:00
437    202406.0                                2024-06-01 00:00:00
438    202407.0                                2024-07-01 00:00:00
439    202408.0                                2024-08-01 00:00:00
440    202409.0                                2024-09-01 00:00:00
441    202410.0                                2024-10-01 00:00:00
442    202411.0                                2024-11-01 00:00:00
443    202412.0                                2024-12-01 00:00:00
444    202501.0                                2025-01-01 00:00:00
445    202502.0                                2025-02-01 00:00:00
446    202503.0                                2025-03-01 00:00:00
447    202504.0                                2025-04-01 00:00:00
448    202505.0                                2025-05-01 00:00:00
449    202506.0                                2025-06-01 00:00:00
450    202507.0                                2025-07-01 00:00:00
451    202508.0                                2025-08-01 00:00:00
452         NaN                                                NaN
453         NaN  Key:    - zero or negligible ..  not available...
454         NaN                                                NaN
455         1.0  Following a minor correction of the method use...
456         NaN  seasonal items that affects lower-level aggreg...
457         NaN  owner occupiers’ housing costs (CPIH) annual g...
458         NaN  In line with our consumer prices revisions and...
459         NaN  This error is isolated to the imputation proce...
460         NaN  including building a more robust production sy...
461         NaN                                                NaN
462         2.0  An error has been identified in the implementa...
463         NaN  This error has no impact on headline Consumer ...
464         NaN  This minor error has no impact on growth rates...
465         NaN  However, a small number of classes within two ...
466         NaN  have seen annual growth impacted by up to 0.1 ...
467         NaN  More details on the lower-level impacts can be...
468         NaN  https://www.ons.gov.uk/economy/inflationandpri...
469         NaN                                                NaN
470         3.0  In December 2018, we published extended series...
471         NaN  and services analyses (included in columns DY ...
472         NaN  of the ongoing accredited official statistics ...
473         NaN                                                NaN
474         4.0  From the release of January consumer price inf...
475         NaN  Full historic series for each of the re-refere...
476         NaN  Regular re-referencing of indices is methodolo...
477         NaN  Please note that re-referencing does not impac...
478         NaN  it is important to use indices that are refere...
479         NaN  For more information, please contact cpi@ons.g...

     Cpih All Items  Food And Non-Alcoholic Beverages     Food  \
430         130.049                           134.781  134.630
431         130.549                           135.465  135.275
432         130.036                           134.929  134.763
433         130.838                           135.241  135.060
434         131.592                           135.493  135.222
435         132.243                           135.928  135.700
436         132.728                           135.562  135.379
437         132.985                           135.833  135.391
438         132.935                           135.861  135.673
439         133.405                           136.183  135.872
440         133.513                           136.680  136.320
441         134.327                           136.877  136.448
442         134.614                           137.509  137.185
443         135.070                           138.170  137.905
444         135.050                           139.369  138.901
445         135.625                           139.684  139.238
446         136.091                           139.619  139.209
447         137.712                           140.588  139.989
448         137.996                           141.551  141.006
449         138.428                           142.013  141.364
450         138.468                           142.584  141.909
451         138.867                           143.160  142.423
452             NaN                               NaN      NaN
453             NaN                               NaN      NaN
454             NaN                               NaN      NaN
455             NaN                               NaN      NaN
456             NaN                               NaN      NaN
457             NaN                               NaN      NaN
458             NaN                               NaN      NaN
459             NaN                               NaN      NaN
460             NaN                               NaN      NaN
461             NaN                               NaN      NaN
462             NaN                               NaN      NaN
463             NaN                               NaN      NaN
464             NaN                               NaN      NaN
465             NaN                               NaN      NaN
466             NaN                               NaN      NaN
467             NaN                               NaN      NaN
468             NaN                               NaN      NaN
469             NaN                               NaN      NaN
470             NaN                               NaN      NaN
471             NaN                               NaN      NaN
472             NaN                               NaN      NaN
473             NaN                               NaN      NaN
474             NaN                               NaN      NaN
475             NaN                               NaN      NaN
476             NaN                               NaN      NaN
477             NaN                               NaN      NaN
478             NaN                               NaN      NaN
479             NaN                               NaN      NaN

     Bread & Cereals     Meat     Fish  Milk, Cheese & Eggs  Oils & Fats  ...  \
430          135.501  126.953  138.165              140.854      173.709  ...
431          137.569  127.249  136.936              141.567      176.052  ...
432          135.821  126.425  134.149              141.080      173.290  ...
433          136.203  126.808  133.759              141.221      176.285  ...
434          136.467  126.192  132.605              140.254      176.975  ...
435          136.852  126.821  133.588              140.196      180.714  ...
436          135.632  127.210  133.537              141.258      183.472  ...
437          136.036  126.869  133.973              140.387      184.376  ...
438          135.848  127.197  133.466              141.844      184.046  ...
439          136.371  127.763  131.458              141.004      187.109  ...
440          136.038  127.820  134.181              141.606      187.465  ...
441          136.106  127.829  132.271              141.526      187.015  ...
442          137.349  127.089  133.411              143.485      190.346  ...
443          138.316  127.241  132.359              143.690      193.049  ...
444          138.878  129.320  132.846              144.162      190.974  ...
445          139.983  129.181  132.838              143.262      191.251  ...
446          140.541  128.802  129.732              144.417      190.071  ...
447          141.386  131.338  130.651              143.479      193.193  ...
448          140.389  133.296  133.653              145.792      190.448  ...
449          141.955  134.114  133.465              145.803      193.836  ...
450          141.981  134.980  131.126              146.607      193.338  ...
451          141.622  135.658  132.059              146.938      190.805  ...
452              NaN      NaN      NaN                  NaN          NaN  ...
453              NaN      NaN      NaN                  NaN          NaN  ...
454              NaN      NaN      NaN                  NaN          NaN  ...
455              NaN      NaN      NaN                  NaN          NaN  ...
456              NaN      NaN      NaN                  NaN          NaN  ...
457              NaN      NaN      NaN                  NaN          NaN  ...
458              NaN      NaN      NaN                  NaN          NaN  ...
459              NaN      NaN      NaN                  NaN          NaN  ...
460              NaN      NaN      NaN                  NaN          NaN  ...
461              NaN      NaN      NaN                  NaN          NaN  ...
462              NaN      NaN      NaN                  NaN          NaN  ...
463              NaN      NaN      NaN                  NaN          NaN  ...
464              NaN      NaN      NaN                  NaN          NaN  ...
465              NaN      NaN      NaN                  NaN          NaN  ...
466              NaN      NaN      NaN                  NaN          NaN  ...
467              NaN      NaN      NaN                  NaN          NaN  ...
468              NaN      NaN      NaN                  NaN          NaN  ...
469              NaN      NaN      NaN                  NaN          NaN  ...
470              NaN      NaN      NaN                  NaN          NaN  ...
471              NaN      NaN      NaN                  NaN          NaN  ...
472              NaN      NaN      NaN                  NaN          NaN  ...
473              NaN      NaN      NaN                  NaN          NaN  ...
474              NaN      NaN      NaN                  NaN          NaN  ...
475              NaN      NaN      NaN                  NaN          NaN  ...
476              NaN      NaN      NaN                  NaN          NaN  ...
477              NaN      NaN      NaN                  NaN          NaN  ...
478              NaN      NaN      NaN                  NaN          NaN  ...
479              NaN      NaN      NaN                  NaN          NaN  ...

     Energy, Food, Alcohol & Tobacco  Energy & Non-Processed Food  \
430                          144.686                      149.544
431                          144.462                      147.774
432                          145.530                      149.084
433                          146.141                      150.017
434                          146.835                      150.641
435                          144.324                      145.541
436                          144.201                      145.540
437                          143.701                      144.393
438                          142.051                      140.993
439                          141.879                      140.201
440                          141.365                      139.092
441                          143.089                      142.308
442                          143.924                      142.541
443                          144.498                      143.265
444                          146.113                      144.617
445                          146.828                      145.195
446                          146.648                      144.598
447                          147.900                      146.064
448                          148.125                      146.066
449                          148.424                      146.072
450                          147.833                      144.489
451                          148.284                      144.842
452                              NaN                          NaN
453                              NaN                          NaN
454                              NaN                          NaN
455                              NaN                          NaN
456                              NaN                          NaN
457                              NaN                          NaN
458                              NaN                          NaN
459                              NaN                          NaN
460                              NaN                          NaN
461                              NaN                          NaN
462                              NaN                          NaN
463                              NaN                          NaN
464                              NaN                          NaN
465                              NaN                          NaN
466                              NaN                          NaN
467                              NaN                          NaN
468                              NaN                          NaN
469                              NaN                          NaN
470                              NaN                          NaN
471                              NaN                          NaN
472                              NaN                          NaN
473                              NaN                          NaN
474                              NaN                          NaN
475                              NaN                          NaN
476                              NaN                          NaN
477                              NaN                          NaN
478                              NaN                          NaN
479                              NaN                          NaN

     Energy & Seasonal Food  Education, Health & Social Protection  \
430                 154.592                                133.121
431                 152.284                                133.426
432                 154.111                                134.111
433                 155.174                                134.272
434                 156.099                                134.586
435                 149.618                                135.199
436                 149.522                                135.437
437                 148.181                                135.891
438                 143.882                                136.085
439                 142.761                                136.450
440                 141.371                                137.694
441                 145.359                                139.947
442                 145.830                                140.046
443                 146.691                                140.375
444                 147.864                                142.324
445                 148.613                                142.583
446                 147.965                                142.866
447                 149.169                                143.198
448                 148.700                                143.501
449                 148.510                                143.782
450                 146.343                                143.520
451                 146.616                                143.932
452                     NaN                                    NaN
453                     NaN                                    NaN
454                     NaN                                    NaN
455                     NaN                                    NaN
456                     NaN                                    NaN
457                     NaN                                    NaN
458                     NaN                                    NaN
459                     NaN                                    NaN
460                     NaN                                    NaN
461                     NaN                                    NaN
462                     NaN                                    NaN
463                     NaN                                    NaN
464                     NaN                                    NaN
465                     NaN                                    NaN
466                     NaN                                    NaN
467                     NaN                                    NaN
468                     NaN                                    NaN
469                     NaN                                    NaN
470                     NaN                                    NaN
471                     NaN                                    NaN
472                     NaN                                    NaN
473                     NaN                                    NaN
474                     NaN                                    NaN
475                     NaN                                    NaN
476                     NaN                                    NaN
477                     NaN                                    NaN
478                     NaN                                    NaN
479                     NaN                                    NaN

     Cpih Excluding Tobacco  Industrial Goods  \
430                 129.528           127.872
431                 129.938           127.394
432                 129.404           126.559
433                 130.189           127.537
434                 130.921           128.347
435                 131.564           126.758
436                 132.048           126.905
437                 132.308           126.283
438                 132.256           124.735
439                 132.726           125.056
440                 132.837           125.283
441                 133.660           126.578
442                 133.883           126.759
443                 134.328           127.152
444                 134.287           126.432
445                 134.841           126.860
446                 135.301           127.409
447                 136.930           127.602
448                 137.213           128.092
449                 137.648           127.960
450                 137.684           126.729
451                 138.088           127.276
452                     NaN               NaN
453                     NaN               NaN
454                     NaN               NaN
455                     NaN               NaN
456                     NaN               NaN
457                     NaN               NaN
458                     NaN               NaN
459                     NaN               NaN
460                     NaN               NaN
461                     NaN               NaN
462                     NaN               NaN
463                     NaN               NaN
464                     NaN               NaN
465                     NaN               NaN
466                     NaN               NaN
467                     NaN               NaN
468                     NaN               NaN
469                     NaN               NaN
470                     NaN               NaN
471                     NaN               NaN
472                     NaN               NaN
473                     NaN               NaN
474                     NaN               NaN
475                     NaN               NaN
476                     NaN               NaN
477                     NaN               NaN
478                     NaN               NaN
479                     NaN               NaN

     Miscellaneous And Other Services  \
430                           122.385
431                           122.320
432                           123.295
433                           123.257
434                           123.461

In [166]:
df.tail

<bound method NDFrame.tail of      Index Date                                               Name  \
0      198801.0                                1988-01-01 00:00:00
1      198802.0                                1988-02-01 00:00:00
2      198803.0                                1988-03-01 00:00:00
3      198804.0                                1988-04-01 00:00:00
4      198805.0                                1988-05-01 00:00:00
..          ...                                                ...
475         NaN  Full historic series for each of the re-refere...
476         NaN  Regular re-referencing of indices is methodolo...
477         NaN  Please note that re-referencing does not impac...
478         NaN  it is important to use indices that are refere...
479         NaN  For more information, please contact cpi@ons.g...

     Cpih All Items  Food And Non-Alcoholic Beverages    Food  \
0            46.851                            47.901  48.244
1            46.998                            48.174  48.501
2            47.202                            48.324  48.643
3            47.801                            48.592  48.894
4            48.044                            48.714  48.968
..              ...                               ...     ...
475             NaN                               NaN     NaN
476             NaN                               NaN     NaN
477             NaN                               NaN     NaN
478             NaN                               NaN     NaN
479             NaN                               NaN     NaN

     Bread & Cereals    Meat    Fish  Milk, Cheese & Eggs  Oils & Fats  ...  \
0             50.053  53.741  43.321               48.488       45.461  ...
1             50.353  53.386  43.670               48.523       45.921  ...
2             50.311  53.721  43.130               48.551       46.108  ...
3             50.548  53.736  43.151               48.861       46.249  ...
4             50.970  54.186  42.799               48.770       46.346  ...
..               ...     ...     ...                  ...          ...  ...
475              NaN     NaN     NaN                  NaN          NaN  ...
476              NaN     NaN     NaN                  NaN          NaN  ...
477              NaN     NaN     NaN                  NaN          NaN  ...
478              NaN     NaN     NaN                  NaN          NaN  ...
479              NaN     NaN     NaN                  NaN          NaN  ...

     Energy, Food, Alcohol & Tobacco  Energy & Non-Processed Food  \
0                             36.679                       37.044
1                             36.761                       37.084
2                             36.831                       37.144
3                             37.198                       37.531
4                             37.360                       37.688
..                               ...                          ...
475                              NaN                          NaN
476                              NaN                          NaN
477                              NaN                          NaN
478                              NaN                          NaN
479                              NaN                          NaN

     Energy & Seasonal Food  Education, Health & Social Protection  \
0                    33.852                                 22.323
1                    33.968                                 22.340
2                    33.976                                 22.455
3                    34.434                                 22.510
4                    34.535                                 22.544
..                      ...                                    ...
475                     NaN                                    NaN
476                     NaN                                    NaN
477                     NaN                                    NaN
478                     NaN                                    NaN
479                     NaN                                    NaN

     Cpih Excluding Tobacco  Industrial Goods  \
0                    48.106            78.883
1                    48.259            79.037
2                    48.476            79.399
3                    49.085            80.067
4                    49.336            80.623
..                      ...               ...
475                     NaN               NaN
476                     NaN               NaN
477                     NaN               NaN
478                     NaN               NaN
479                     NaN               NaN

     Miscellaneous And Other Services  \
0                              26.778
1                              26.915
2                              26.968
3                              27.098
4                              27.213
..                                ...
475                               NaN
476                               NaN
477                               NaN
478                               NaN
479                               NaN

     Cpih Excluding Owner Occupiers' Housing Costs  \
0                                           47.734
1                                           47.884
2                                           48.042
3                                           48.707
4                                           48.941
..                                             ...
475                                            NaN
476                                            NaN
477                                            NaN
478                                            NaN
479                                            NaN

     Cpih Excluding Council Tax  \
0                        47.304
1                        47.455
2                        47.667
3                        48.184
4                        48.435
..                          ...
475                         NaN
476                         NaN
477                         NaN
478                         NaN
479                         NaN

     Cpih Excluding Owner Occupiers' Housing Costs And Council Tax And Rates
0                                               48.329
1                                               48.486
2                                               48.652
3                                               49.214
4                                               49.459
..                                                 ...
475                                                NaN
476                                                NaN
477                                                NaN
478                                                NaN
479                                                NaN

[480 rows x 181 columns]>

In [167]:
df.drop(df.index[452:], inplace=True)
df = df.reset_index(drop=True)
df

,Index Date,Name,Cpih All Items,Food And Non-Alcoholic Beverages,Food,Bread & Cereals,Meat,Fish,"Milk, Cheese & Eggs",Oils & Fats,...,"Energy, Food, Alcohol & Tobacco",Energy & Non-Processed Food,Energy & Seasonal Food,"Education, Health & Social Protection",Cpih Excluding Tobacco,Industrial Goods,Miscellaneous And Other Services,Cpih Excluding Owner Occupiers' Housing Costs,Cpih Excluding Council Tax,Cpih Excluding Owner Occupiers' Housing Costs And Council Tax And Rates
0,198801.0,1988-01-01 00:00:00,46.851,47.901,48.244,50.053,53.741,43.321,48.488,45.461,...,36.679,37.044,33.852,22.323,48.106,78.883,26.778,47.734,47.304,48.329
1,198802.0,1988-02-01 00:00:00,46.998,48.174,48.501,50.353,53.386,43.670,48.523,45.921,...,36.761,37.084,33.968,22.340,48.259,79.037,26.915,47.884,47.455,48.486
2,198803.0,1988-03-01 00:00:00,47.202,48.324,48.643,50.311,53.721,43.130,48.551,46.108,...,36.831,37.144,33.976,22.455,48.476,79.399,26.968,48.042,47.667,48.652
3,198804.0,1988-04-01 00:00:00,47.801,48.592,48.894,50.548,53.736,43.151,48.861,46.249,...,37.198,37.531,34.434,22.510,49.085,80.067,27.098,48.707,48.184,49.214
4,198805.0,1988-05-01 00:00:00,48.044,48.714,48.968,50.970,54.186,42.799,48.770,46.346,...,37.360,37.688,34.535,22.544,49.336,80.623,27.213,48.941,48.435,49.459
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
447,202504.0,2025-04-01 00:00:00,137.712,140.588,139.989,141.386,131.338,130.651,143.479,193.193,...,147.900,146.064,149.169,143.198,136.930,127.602,131.032,138.748,137.341,138.342
448,202505.0,2025-05-01 00:00:00,137.996,141.551,141.006,140.389,133.296,133.653,145.792,190.448,...,148.125,146.066,148.700,143.501,137.213,128.092,131.345,138.978,137.634,138.580
449,202506.0,2025-06-01 00:00:00,138.428,142.013,141.364,141.955,134.114,133.465,145.803,193.836,...,148.424,146.072,148.510,143.782,137.648,127.960,131.577,139.411,138.077,139.028
450,202507.0,2025-07-01 00:00:00,138.468,142.584,141.909,141.981,134.980,131.126,146.607,193.338,...,147.833,144.489,146.343,143.520,137.684,126.729,131.224,139.498,138.118,139.118
451,202508.0,2025-08-01 00:00:00,138.867,143.160,142.423,141.622,135.658,132.059,146.938,190.805,...,148.284,144.842,146.616,143.932,138.088,127.276,131.453,139.874,138.528,139.506

In [168]:
df_CPIH = df[['Cpih All Items']]

df_CPIH.tail

<bound method NDFrame.tail of      Cpih All Items
0            46.851
1            46.998
2            47.202
3            47.801
4            48.044
..              ...
447         137.712
448         137.996
449         138.428
450         138.468
451         138.867

[452 rows x 1 columns]>

In [169]:
df_CPIH['Cpih All Items'] = df_CPIH.groupby(df_CPIH.index // 3)['Cpih All Items'].mean()
df_CPIH = df_CPIH.dropna()
df_CPIH.reset_index(drop=True)
df_CPIH

C:\Users\David\AppData\Local\Temp\ipykernel_36564\1083017060.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_CPIH['Cpih All Items'] = df_CPIH.groupby(df_CPIH.index // 3)['Cpih All Items'].mean()

     Cpih All Items
0         47.017000
1         48.018333
2         48.480000
3         49.229667
4         49.757000
..              ...
146      133.284333
147      134.670333
148      135.588667
149      138.045333
150      138.667500

[151 rows x 1 columns]

In [175]:
df_CPIH ['Percentage_Change'] = (df_CPIH['Cpih All Items'].pct_change() * 100).round(1)
df_CPIH['Percentage_Change'].fillna(0, inplace=True)

C:\Users\David\AppData\Local\Temp\ipykernel_36564\2183895583.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_CPIH ['Percentage_Change'] = (df_CPIH['Cpih All Items'].pct_change() * 100).round(1)
C:\Users\David\AppData\Local\Temp\ipykernel_36564\2183895583.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_CPIH['Percentage_Change'].fillna(0, inplace=True)
C:\Users\David\AppData\Local\Temp\ipykernel_36564\2183895583.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_CPIH['Percentage_Change'].fillna(0, inplace=True)

In [176]:
df_CPIH

     Cpih All Items  Percentage_Change
0         47.017000                0.0
1         48.018333                2.1
2         48.480000                1.0
3         49.229667                1.5
4         49.757000                1.1
..              ...                ...
146      133.284333                0.5
147      134.670333                1.0
148      135.588667                0.7
149      138.045333                1.8
150      138.667500                0.5

[151 rows x 2 columns]

In [177]:
df_CPIH.to_excel("C:\\Git_test\\Project 2 Docs\\Data Sets\\CPI_ons_data_transformed_CPIH_all.xlsx", index=False)